version: "3.7"
services:
  react-context-cicd:
    image: react-context-cicd
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "9876:80"
    networks:
      - default
    deploy:
      mode: replicated
      replicas: 1
networks:
  default:
    external:
      name: swarm_network
