version: "3.7"
services:
  react-context-circleci:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "9876:80"
    networks:
      - default

networks:
  default:
    external:
      name: swarm_network
