version: 2.1
orbs:
  node: circleci/node@4.7

# Define the jobs we want to run for this project
jobs:
  pull-and-build:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: 
            - "35:50:e0:50:50:d8:ec:6f:25:d9:c4:4b:c7:10:85:9c"
      - run: echo $USER@$HOST
      - run: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - master
  