version: 2.1
orbs:
  node: circleci/node@4.7

# Define the jobs we want to run for this project
jobs:
  pull-and-build:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
<<<<<<< HEAD
      - run: echo $USER@$HOST
=======
      - run echo $USER@$HOST 
>>>>>>> e8f2ec3174f27a57aa2ba174e5090b09dc3b9e22
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$HOST "chmod +x deploy.sh; ./deploy.sh"

# Orchestrate our job run sequence
 workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - master
  