version: 2.1
orbs:
  node: circleci/node@4.7

# Define the jobs we want to run for this project
jobs:
  pull-and-build:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$HOST "chmod +x deploy.sh; ./deploy.sh"

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - master
  # push-job:
  #   docker:
  #     - image: cimg/node:16.10
  #   steps:
  #     - checkout

  #     - node/install-packages:
     
  #         pkg-manager: npm
  #     - run:
  #         name: Run tests
  #         command: npm test

  # deploy-job:
  #   docker:
  #     - image: cimg/node:16.10
  #   steps:
  #     - checkout

  #     - node/install-packages:
     
  #         pkg-manager: npm
  #     - run:
  #         name: Run tests
  #         command: npm test

# workflows:
#   -deploy:
#     jobs:
#       - build-job
      # - push-job
      # - deploy-job:
      #     requires:
      #       - build-job
      #       - push-job
      #     filters:
      #       branches:
      #         only: master
