version: 2.1
orbs:
  node: circleci/node@4.7

# Define the jobs we want to run for this project
jobs:
  pull-and-build:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run: echo $USER@$HOST
      - run: echo 52:65:1d:d8:e6:92:6b:31:5f:e7:65:ab:c1:48:ab:1b
      # - run: ssh test@35.197.150.4 "./deploy.sh"

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - master
  