version: 2.1

# Define the jobs we want to run for this project
jobs:
  pull-and-build:
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: 
            - "35:50:e0:50:50:d8:ec:6f:25:d9:c4:4b:c7:10:85:9c"
      - run: ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
      # - run: ssh  $USER@$HOST cd $PROJECT_NAME; bash deploy.sh 
      - run: ssh  $USER@$HOST "cd $(PROJECT_NAME); bash deploy.sh"

# Orchestrate our job run sequence
workflows:
  version: 2
  build-project:
    jobs:
      - pull-and-build:
          filters:
            branches:
              only:
                - master
  