orbs:
  node: circleci/node@4.2.1

version: 2.1

jobs:
   build:
      docker:
        - image: docker
      steps:
        - setup_remote_docker:
            docker_layer_caching: true
        - run: docker image ls
        - run: docker volume ls
        - run: docker run --mount source=datastore,destination=/mnt/volume debian:bullseye-slim dd if=/dev/zero of=/mnt/volume/zero bs=32M count=32
        - run: docker volume ls

workflows:
  app-tests:
    jobs:
      - build





# version: 2.1

# orbs:
#   node: circleci/node@4.7

# jobs:
#   build-job:
#     docker:
#       - image: cimg/node:16.10

#     working_directory: ~/repo
#     steps:
#       - checkout

#       - node/install-packages:
#           pkg-manager: npm
#       - run:
#           name: Run tests
#           command: npm test

#   push-job:
#     docker:
#       - image: cimg/node:16.10
#     steps:
#       - checkout

#       - node/install-packages:
     
#           pkg-manager: npm
#       - run:
#           name: Run tests
#           command: npm test

#   deploy-job:
#     docker:
#       - image: cimg/node:16.10
#     steps:
#       - checkout

#       - node/install-packages:
     
#           pkg-manager: npm
#       - run:
#           name: Run tests
#           command: npm test

# workflows:
#   version: 2
#   -deploy:
#     jobs:
#       - build-job
#       - push-job
#       - deploy-job:
#           requires:
#             - build-job
#             - push-job
#           filters:
#             branches:
#               only: master
