version: 2.1
# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run: echo "build"
      - run: echo $CIRCLE_TAG
  test:
    docker:
      - image: arvindr226/alpine-ssh
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run: echo "test"
      - run: echo $CIRCLE_TAG
  deploy:
    docker:
      - image: arvindr226/alpine-ssh
    environment:
      DEV_SSH: ssh $USER@$HOST
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - run: echo $CIRCLE_TAG
      - run: echo "deploy"
      - run: echo $DEV_SSH $USER@$HOST
      - add_ssh_keys:
          fingerprints: 
            - "35:50:e0:50:50:d8:ec:6f:25:d9:c4:4b:c7:10:85:9c"
      - run: ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
      - run: ssh $USER@$HOST "cd $PROJECT_NAME; git tag -d $(git tag); git pull; git checkout tags/$CIRCLE_TAG -b master_$CIRCLE_TAG; ls; bash deploy.sh"
      - run: ssh $USER@$HOST "cd $PROJECT_NAME; git branch"
      - run: ssh $USER@$HOST "cd $PROJECT_NAME; git checkout master"

# Orchestrate our job run sequence
workflows:
  version: 2
  deploy-project:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - dev
      - test:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - deploy:
          filters:
            tags:
              only: /^v.*/ 
            branches:
              ignore: /.*/
            # branches:
            #   only:
            #     - master
            
  